# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2019-2026 Second State INC

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "driver",
    srcs = [
        "compilerTool.cpp",
        "fuzzPO.cpp",
        "fuzzTool.cpp",
        "runtimeTool.cpp",
        "uniTool.cpp",
    ],
    hdrs = glob(["../../include/driver/*.h"]),
    includes = ["../../include"],
    deps = [
        "//lib/vm",
    ],
)
